
- name: Start Playbook
  hosts: localhost
  become: true

  pre_tasks:
    - name: Gather EC2 metadata
      ec2_metadata_facts:


  tasks:
    - name: First Test Output
      debug: msg="Start Playbook Running"

    - name: Try writing a file to see if this is actually running
      file:
        path: /opt/cochran
        state: directory
        mode: '0755'